---
kind: pipeline
name: default-linux-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: rancher/dapper:v0.5.4
  commands:
  - dapper ci
  privileged: true
  volumes:
  - name: docker
    path: /var/run/docker.sock
  when:
    event:
    - push
    - pull_request
    - tag

- name: stage-binaries
  image: rancher/dapper:v0.5.4
  commands:
  - "cp -r ./bin/* ./package/"
  when:
    event:
    - push
    - tag

- name: docker-publish
  image: plugins/docker
  settings:
    purge: false
    build_args:
    - ARCH=amd64
    - "VERSION=${DRONE_TAG}"
    context: package/
    custom_dns: 1.1.1.1
    dockerfile: package/Dockerfile
    password:
      from_secret: docker_password
    repo: rancher/drone-docker-image-digests
    tag: "${DRONE_TAG}-linux-amd64"
    username:
      from_secret: docker_username
  when:
    event:
    - tag

- name: github_binary_prerelease
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    checksum:
    - sha256
    files:
    - "bin/drone-docker-image-digests*"
    prerelease: true
  when:
    event:
    - tag
    ref:
      include:
      - "refs/tags/*rc*"
      - "refs/tags/*alpha*"

- name: github_binary_release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    checksum:
    - sha256
    files:
    - "bin/drone-docker-image-digests*"
  when:
    event:
    - tag
    ref:
      exclude:
      - "refs/tags/*rc*"
      - "refs/tags/*alpha*"

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

---
kind: pipeline
name: default-linux-arm64

platform:
  os: linux
  arch: arm64

steps:
- name: build
  image: rancher/dapper:v0.5.4
  commands:
  - dapper ci
  privileged: true
  volumes:
  - name: docker
    path: /var/run/docker.sock
  when:
    event:
    - push
    - pull_request
    - tag

- name: stage-binaries
  image: rancher/dapper:v0.5.4
  commands:
  - "cp -r ./bin/* ./package/"
  when:
    event:
    - push
    - tag

- name: docker-publish
  image: plugins/docker
  settings:
    purge: false
    build_args:
    - ARCH=arm64
    - "VERSION=${DRONE_TAG}"
    context: package/
    custom_dns: 1.1.1.1
    dockerfile: package/Dockerfile
    password:
      from_secret: docker_password
    repo: rancher/drone-docker-image-digests
    tag: "${DRONE_TAG}-linux-arm64"
    username:
      from_secret: docker_username
  when:
    event:
    - tag

volumes:
- name: docker
  host:
    path: /var/run/docker.sock
---
kind: pipeline
name: default-windows-1809

platform:
  os: windows
  arch: amd64
  version: 1809

steps:
  - name: build
    pull: always
    image: rancher/dapper:v0.5.4
    commands:
      - dapper.exe -f Dockerfile-windows.dapper -d ci
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine
    when:
      event:
        - push
        - pull_request
        - tag

  - name: stage-binaries
    image: rancher/dapper:v0.5.4
    commands:
      - "cp -r ./bin/* ./package/windows/"
    when:
      event:
        - push
        - tag

  - name: docker-publish
    image: plugins/docker:windows-1809-amd64
    settings:
      purge: false
      build_args:
        - SERVERCORE_VERSION=1809
        - ARCH=amd64
        - "VERSION=${DRONE_TAG}"
      context: package/windows
      custom_dns: 1.1.1.1
      dockerfile: package/windows/Dockerfile
      password:
        from_secret: docker_password
      repo: rancher/drone-docker-image-digests
      tag: "${DRONE_TAG}-windows-1809"
      username:
        from_secret: docker_username
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine
    when:
      event:
        - tag

volumes:
  - name: docker_pipe
    host:
      path: \\\\.\\pipe\\docker_engine

---
kind: pipeline
name: default-windows-1903

platform:
  os: windows
  arch: amd64
  version: 1903

steps:
  - name: build
    pull: always
    image: rancher/dapper:v0.5.4
    commands:
      - dapper.exe -f Dockerfile-windows.dapper -d ci
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine
    when:
      event:
        - push
        - pull_request
        - tag

  - name: stage-binaries
    image: rancher/dapper:v0.5.4
    commands:
      - "cp -r ./bin/* ./package/windows/"
    when:
      event:
        - push
        - tag

  - name: docker-publish
    image: plugins/docker:windows-1903-amd64
    settings:
      purge: false
      build_args:
        - SERVERCORE_VERSION=1903
        - ARCH=amd64
        - "VERSION=${DRONE_TAG}"
      context: package/windows
      custom_dns: 1.1.1.1
      dockerfile: package/windows/Dockerfile
      password:
        from_secret: docker_password
      repo: rancher/drone-docker-image-digests
      tag: "${DRONE_TAG}-windows-1903"
      username:
        from_secret: docker_username
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine
    when:
      event:
        - tag

volumes:
  - name: docker_pipe
    host:
      path: \\\\.\\pipe\\docker_engine

---
kind: pipeline
name: default-windows-1909

platform:
  os: windows
  arch: amd64
  version: 1909

steps:
  - name: build
    pull: always
    image: rancher/dapper:v0.5.4
    commands:
      - dapper.exe -f Dockerfile-windows.dapper -d ci
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine
    when:
      event:
        - push
        - pull_request
        - tag

  - name: stage-binaries
    image: rancher/dapper:v0.5.4
    commands:
      - "cp -r ./bin/* ./package/windows/"
    when:
      event:
        - push
        - tag

  - name: docker-publish
    image: plugins/docker:windows-1909-amd64
    settings:
      purge: false
      build_args:
        - SERVERCORE_VERSION=1909
        - ARCH=amd64
        - "VERSION=${DRONE_TAG}"
      context: package/windows
      custom_dns: 1.1.1.1
      dockerfile: package/windows/Dockerfile
      password:
        from_secret: docker_password
      repo: rancher/drone-docker-image-digests
      tag: "${DRONE_TAG}-windows-1909"
      username:
        from_secret: docker_username
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine
    when:
      event:
        - tag

volumes:
  - name: docker_pipe
    host:
      path: \\\\.\\pipe\\docker_engine

---
kind: pipeline
name: default-windows-2004

platform:
  os: windows
  arch: amd64
  version: 2004

# remove this and use upstream images when https://github.com/drone/drone-git/pull/25 is merged
clone:
  disable: true

steps:
  - name: clone
    image: luthermonson/drone-git:windows-2004-amd64
    settings:
      depth: 1
  - name: build
    pull: always
    image: rancher/dapper:v0.5.4
    commands:
      - dapper.exe -f Dockerfile-windows.dapper -d ci
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine
    when:
      event:
        - push
        - pull_request
        - tag

  - name: stage-binaries
    image: rancher/dapper:v0.5.4
    commands:
      - "cp -r ./bin/* ./package/windows/"
    when:
      event:
        - push
        - tag

  - name: docker-publish
    image: luthermonson/drone-docker:2004
    settings:
      purge: false
      build_args:
        - SERVERCORE_VERSION=2004
        - ARCH=amd64
        - "VERSION=${DRONE_TAG}"
      context: package/windows
      custom_dns: 1.1.1.1
      dockerfile: package/windows/Dockerfile
      password:
        from_secret: docker_password
      repo: rancher/drone-docker-image-digests
      tag: "${DRONE_TAG}-windows-2004"
      username:
        from_secret: docker_username
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine
    when:
      event:
        - tag

volumes:
  - name: docker_pipe
    host:
      path: \\\\.\\pipe\\docker_engine

---
kind: pipeline
name: default-windows-20H2

platform:
  os: windows
  arch: amd64
  version: 20H2

# remove this and use upstream images when https://github.com/drone/drone-git/pull/25 is merged
clone:
  disable: true

steps:
  - name: clone
    image: luthermonson/drone-git:windows-20H2-amd64
    settings:
      depth: 1
  - name: build
    pull: always
    image: rancher/dapper:v0.5.4
    commands:
      - dapper.exe -f Dockerfile-windows.dapper -d ci
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine
    when:
      event:
        - push
        - pull_request
        - tag

  - name: stage-binaries
    image: rancher/dapper:v0.5.4
    commands:
      - "cp -r ./bin/* ./package/windows/"
    when:
      event:
        - push
        - tag

  - name: docker-publish
    image: luthermonson/drone-docker:20H2
    settings:
      purge: false
      build_args:
        - SERVERCORE_VERSION=20H2
        - ARCH=amd64
        - "VERSION=${DRONE_TAG}"
      context: package/windows
      custom_dns: 1.1.1.1
      dockerfile: package/windows/Dockerfile
      password:
        from_secret: docker_password
      repo: rancher/drone-docker-image-digests
      tag: "${DRONE_TAG}-windows-20H2"
      username:
        from_secret: docker_username
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine
    when:
      event:
        - tag

volumes:
  - name: docker_pipe
    host:
      path: \\\\.\\pipe\\docker_engine

---
kind: pipeline
name: manifest

steps:
- name: push-manifest
  image: plugins/manifest
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    spec: manifest.tmpl
  when:
    instance:
      include:
      - drone-publish.rancher.io
    event:
    - push
    - tag

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

depends_on:
- default-linux-amd64
- default-linux-arm64
- default-windows-1809
- default-windows-1903
- default-windows-1909
- default-windows-2004
- default-windows-20H2
