---
kind: pipeline
name: default-linux-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: rancher/dapper:v0.5.5
  environment:
    CROSS: "windows"
  commands:
  - dapper ci
  privileged: true
  volumes:
  - name: docker
    path: /var/run/docker.sock
  when:
    event:
    - push
    - pull_request
    - tag

- name: docker-publish
  image: plugins/docker
  settings:
    purge: false
    build_args:
    - ARCH=amd64
    - "VERSION=${DRONE_TAG}"
    custom_dns: 1.1.1.1
    dockerfile: package/Dockerfile
    password:
      from_secret: docker_password
    repo: rancher/drone-docker-image-digests
    tag: "${DRONE_TAG}-linux-amd64"
    username:
      from_secret: docker_username
  when:
    event:
    - tag

- name: github_binary_prerelease
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    checksum:
    - sha256
    checksum_file: CHECKSUMsum-amd64.txt
    checksum_flatten: true
    files:
    - "dist/artifacts/*"
    prerelease: true
  when:
    event:
    - tag
    ref:
      include:
      - "refs/tags/*rc*"
      - "refs/tags/*alpha*"

- name: github_binary_release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    checksum:
    - sha256
    checksum_file: CHECKSUMsum-amd64.txt
    checksum_flatten: true
    files:
    - "dist/artifacts/*"
  when:
    event:
    - tag
    ref:
      exclude:
      - "refs/tags/*rc*"
      - "refs/tags/*alpha*"

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

---
kind: pipeline
name: default-linux-arm64

platform:
  os: linux
  arch: arm64

steps:
- name: build
  image: rancher/dapper:v0.5.5
  commands:
  - dapper ci
  privileged: true
  volumes:
  - name: docker
    path: /var/run/docker.sock
  when:
    event:
    - push
    - pull_request
    - tag

- name: docker-publish
  image: plugins/docker
  settings:
    purge: false
    build_args:
    - ARCH=arm64
    - "VERSION=${DRONE_TAG}"
    custom_dns: 1.1.1.1
    dockerfile: package/Dockerfile
    password:
      from_secret: docker_password
    repo: rancher/drone-docker-image-digests
    tag: "${DRONE_TAG}-linux-arm64"
    username:
      from_secret: docker_username
  when:
    event:
    - tag

- name: github_binary_prerelease
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    checksum:
    - sha256
    checksum_file: CHECKSUMsum-arm64.txt
    checksum_flatten: true
    files:
    - "dist/artifacts/*"
    prerelease: true
  when:
    event:
    - tag
    ref:
      include:
      - "refs/tags/*rc*"
      - "refs/tags/*alpha*"

volumes:
- name: docker
  host:
    path: /var/run/docker.sock
---
kind: pipeline
name: default-windows-1809

platform:
  os: windows
  arch: amd64
  version: 1809

steps:
  - name: docker-publish
    image: plugins/docker
    settings:
      purge: false
      build_args:
        - "SERVERCORE_VERSION=1809"
        - "VERSION=${DRONE_TAG}"
        - "ARCH=amd64"
      custom_dns: 1.1.1.1
      dockerfile: package/Dockerfile.windows
      password:
        from_secret: docker_password
      repo: rancher/drone-docker-image-digests
      tag: "${DRONE_TAG}-windows-1809"
      username:
        from_secret: docker_username
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine
    when:
      event:
        - tag

volumes:
  - name: docker_pipe
    host:
      path: \\\\.\\pipe\\docker_engine

depends_on:
  - default-linux-amd64
---
kind: pipeline
name: default-windows-1903

platform:
  os: windows
  arch: amd64
  version: 1903

steps:
  - name: docker-publish
    image: plugins/docker
    settings:
      purge: false
      build_args:
        - "SERVERCORE_VERSION=1903"
        - "VERSION=${DRONE_TAG}"
        - "ARCH=amd64"
      custom_dns: 1.1.1.1
      dockerfile: package/Dockerfile.windows
      password:
        from_secret: docker_password
      repo: rancher/drone-docker-image-digests
      tag: "${DRONE_TAG}-windows-1903"
      username:
        from_secret: docker_username
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine
    when:
      event:
        - tag

volumes:
  - name: docker_pipe
    host:
      path: \\\\.\\pipe\\docker_engine

depends_on:
  - default-linux-amd64
---
kind: pipeline
name: default-windows-1909

platform:
  os: windows
  arch: amd64
  version: 1909

steps:
  - name: docker-publish
    image: plugins/docker
    settings:
      purge: false
      build_args:
        - "SERVERCORE_VERSION=1909"
        - "VERSION=${DRONE_TAG}"
        - "ARCH=amd64"
      custom_dns: 1.1.1.1
      dockerfile: package/Dockerfile.windows
      password:
        from_secret: docker_password
      repo: rancher/drone-docker-image-digests
      tag: "${DRONE_TAG}-windows-1909"
      username:
        from_secret: docker_username
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine
    when:
      event:
        - tag

volumes:
  - name: docker_pipe
    host:
      path: \\\\.\\pipe\\docker_engine

depends_on:
  - default-linux-amd64
---
kind: pipeline
name: default-windows-2004

platform:
  os: windows
  arch: amd64
  version: 2004

# remove this and use upstream images when https://github.com/drone/drone-git/pull/25 is merged
clone:
  disable: true

steps:
  - name: clone
    image: luthermonson/drone-git:windows-2004-amd64
    settings:
      depth: 1

  - name: docker-publish
    image: luthermonson/drone-docker:2004
    settings:
      purge: false
      build_args:
        - "SERVERCORE_VERSION=2004"
        - "VERSION=${DRONE_TAG}"
        - "ARCH=amd64"
      custom_dns: 1.1.1.1
      dockerfile: package/Dockerfile.windows
      password:
        from_secret: docker_password
      repo: rancher/drone-docker-image-digests
      tag: "${DRONE_TAG}-windows-2004"
      username:
        from_secret: docker_username
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine
    when:
      event:
        - tag

volumes:
  - name: docker_pipe
    host:
      path: \\\\.\\pipe\\docker_engine

depends_on:
  - default-linux-amd64
---
kind: pipeline
name: default-windows-20H2

platform:
  os: windows
  arch: amd64
  version: 20H2

# remove this and use upstream images when https://github.com/drone/drone-git/pull/25 is merged
clone:
  disable: true

steps:
  - name: clone
    image: luthermonson/drone-git:windows-20H2-amd64
    settings:
      depth: 1

  - name: docker-publish
    image: luthermonson/drone-docker:20H2
    settings:
      purge: false
      build_args:
        - "SERVERCORE_VERSION=20H2"
        - "VERSION=${DRONE_TAG}"
        - "ARCH=amd64"
      custom_dns: 1.1.1.1
      dockerfile: package/Dockerfile.windows
      password:
        from_secret: docker_password
      repo: rancher/drone-docker-image-digests
      tag: "${DRONE_TAG}-windows-20H2"
      username:
        from_secret: docker_username
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine
    when:
      event:
        - tag

volumes:
  - name: docker_pipe
    host:
      path: \\\\.\\pipe\\docker_engine

depends_on:
- default-linux-amd64
---
kind: pipeline
name: manifest

steps:
- name: push-manifest
  image: plugins/manifest
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    spec: manifest.tmpl
  when:
    instance:
      include:
      - drone-publish.rancher.io
    event:
    - tag

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

depends_on:
- default-linux-amd64
- default-linux-arm64
- default-windows-1809
- default-windows-1903
- default-windows-1909
- default-windows-2004
- default-windows-20H2
