#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

mkdir -p bin
if [ "$(uname)" = "Linux" ]; then
    OTHER_LINKFLAGS="-extldflags -static -s"
fi
LINKFLAGS="-X github.com/rancher/drone-docker-image-digests.Version=$VERSION"
LINKFLAGS="-X github.com/rancher/drone-docker-image-digests.GitCommit=$COMMIT $LINKFLAGS"
CGO_ENABLED=0 go build -ldflags "$LINKFLAGS $OTHER_LINKFLAGS" -o bin/drone-docker-image-digests
if [ "$CROSS" = "true" ] && [ "$ARCH" = "amd64" ]; then
    GOOS=darwin go build -ldflags "$LINKFLAGS" -o bin/drone-docker-image-digests-darwin
    GOOS=windows go build -ldflags "$LINKFLAGS" -o bin/drone-docker-image-digests.exe
fi
